services:
  - type: web
    name: hora-certa-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: corepack yarn install --immutable && corepack yarn prisma migrate deploy && corepack yarn prisma db seed && corepack yarn build
    startCommand: corepack yarn start
    envVars:
      - key: JWT_SECRET
        generateValue: true
