// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate needs a direct (non-pooled) connection.
    // The app itself connects via DATABASE_URL (pooled) in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
